/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_raider_book_utils_JniUtils */

#ifndef _Included_com_raider_book_utils_JniUtils
#define _Included_com_raider_book_utils_JniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_raider_book_utils_JniUtils
 * Method:    storeBooksToDB
 * Signature: ()Z
 */
JNIEXPORT jstring JNICALL Java_com_raider_book_utils_JniUtils_storeBooksToDB
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
